model_list:
  - model_name: Qwen3.5-35B-A3B-FP8
    litellm_params:
      model: openai/Qwen3.5-35B-A3B-FP8
      api_base: http://vllm-qwen35-35b-a3b-fp8:8000/v1
      api_key: no_api_key
      rpm: 72
      tpm: 180000

  - model_name: Qwen3-Embedding-0.6B
    litellm_params:
      model: openai/Qwen3-Embedding-0.6B
      api_base: http://vllm-qwen3-embedding-cpu:8001/v1
      api_key: no_api_key
      rpm: 120
      tpm: 240000

  - model_name: bge-reranker-v2-m3
    litellm_params:
      model: openai/bge-reranker-v2-m3
      api_base: http://vllm-qwen3-rerank-cpu:8002/v1
      api_key: no_api_key
      rpm: 120
      tpm: 120000

router_settings:
  routing_strategy: simple-shuffle
  optional_pre_call_checks:
    - enforce_model_rate_limits
  redis_host: os.environ/REDIS_HOST
  redis_port: os.environ/REDIS_PORT
  redis_password: os.environ/REDIS_PASSWORD
  redis_db: os.environ/REDIS_DB

litellm_settings:
  set_verbose: false
  drop_params: true
  request_timeout: 600
  callbacks:
    - prometheus
